### PR TITLE
Hiding component if user is not registered to any events

### PR DESCRIPTION
**Pull request by rosiejeays**
On the profile page - adding in a turnery on the MyEvents component so that a random title of "Events I've registered for" doesn't show if there are no events the user has registered for. :)

### CODE REVIEW

**Comment by oriyannadav** [comment]
I can't check this as I cant see the "select skills" in the apply form which means I don't have any users on my local machine.

**Comment by rosiejeays** [comment]
> I can't check this as I cant see the "select skills" in the apply form which means I don't have any users on my local machine.

@oriyannadav are you able to now that we got your local environment up and running? All good if not :)

**Comment by oriyannadav** [comment]
I tried to view it after I got local fixed. Something in my backend is still not working🤷🏽‍♀️

**Comment by Andrea-Rivera** [comment]
the functionality is fine but the only little thing is that it is currently displaying two apostrophes in the "Events I''ve registered for".  But apart from that it is good.

**Comment by rosiejeays** [comment]
Damn. @mayadomi any chance you're able to review this one?

**Review by Andrea-Rivera — APPROVED** [review]
yes, it is working this part.

**Pull request merged**
